# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build README.md

on:
  push:
    branches: [ github-action ]
  pull_request:
    branches: [ github-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.14.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.0
        cache: 'npm'
    - name: build README.md
      run: npm run build
    - name: update README.md
      run: |
        git add .
        git config --global user.email "dev.timetravel@gmail.com"
        git config --global user.name "cruelladevil"
        git commit -m "Automatic Update README.md"
        git push
